<a href="https://colab.research.google.com/github/Omkar210/Ecommerse-Transaction-EDA/blob/main/eda_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd
# import warnings
# warnings.filterwarnings("ignore")
# pd.set_option('display.max_columns', None)
from numpy import random
from collections import Counter
from numpy.linalg import inv
from numpy.linalg import eig
import matplotlib
from matplotlib import pyplot as plt
import seaborn as sns
import pylab
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel
import scipy
from scipy import stats
from scipy.stats import binom,poisson,norm,t,expon,f
from sklearn.model_selection import train_test_split
import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw
import os
print(os.getcwd())
os.chdir('/content/drive/MyDrive/CDAC')
os.getcwd()

/content/drive/MyDrive/CDAC

'/content/drive/MyDrive/CDAC'

# Load Data

In [17]:
df = pd.read_csv("ecommerce-transactions-raw.csv")
df.head()

,transaction_id,user_id,product_id,product_category,sub_category,product_price,discount_percent,final_price,quantity,transaction_date,...,seller_state,customer_segment,gst_amount,shipping_cost,refund_amount,device_type,browser_type,session_duration_min,has_reviews,loyalty_member
0,TXN_0000000000,131958,PID_193175,Sports,Team Sports,2998.912641,60,1199.565056,4,2022-08-17,...,MH,Premium,863.686841,0.0,4798.260226,Desktop,Edge,19.334006,1,NaN
1,TXN_0000000001,156867,PID_333865,Electronics,Mobile,5220.659851,70,1566.197955,2,2022-02-21,...,HR,Basic,563.831264,0.0,3132.395911,Mobile,Opera,33.591958,0,Yes
2,TXN_0000000002,141932,PID_837148,Furniture,Lighting,9872.169189,45,5429.693054,3,2023-07-18,...,TN,Premium,2932.034249,0.0,NaN,Tablet,Safari,32.615823,0,NaN
3,TXN_0000000003,375838,PID_911087,Books,Self-Help,3144.453832,90,314.445383,1,2023-05-17,...,HR,Basic,15.722269,0.0,NaN,Mobile,Firefox,21.880198,1,NaN
4,TXN_0000000004,269178,PID_728478,Electronics,Smartwatch,727.618316,25,537.578346,1,2023-04-03,...,UP,Standard,96.764102,0.0,NaN,Tablet,Edge,0.916835,1,NaN

# Information about Data

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2030000 entries, 0 to 2029999
Data columns (total 30 columns):
 #   Column                Dtype
---  ------                -----
 0   transaction_id        object
 1   user_id               int64
 2   product_id            object
 3   product_category      object
 4   sub_category          object
 5   product_price         float64
 6   discount_percent      int64
 7   final_price           float64
 8   quantity              int64
 9   transaction_date      object
 10  payment_mode          object
 11  order_status          object
 12  delivery_date         object
 13  delivery_days         float64
 14  return_flag           int64
 15  return_reason         object
 16  return_date           object
 17  seller_rating         float64
 18  customer_rating       float64
 19  buyer_state           object
 20  seller_state          object
 21  customer_segment      object
 22  gst_amount            float64
 23  shipping_cost         float64
 24  refund_amount         float64
 25  device_type           object
 26  browser_type          object
 27  session_duration_min  float64
 28  has_reviews           int64
 29  loyalty_member        object
dtypes: float64(9), int64(5), object(16)
memory usage: 464.6+ MB

In [19]:
df.describe()

,user_id,product_price,discount_percent,final_price,quantity,...,gst_amount,shipping_cost,refund_amount,session_duration_min,has_reviews
count,2.030000e+06,2.030000e+06,2.030000e+06,2.030000e+06,2.030000e+06,...,2.030000e+06,2.009623e+06,304983.000000,2.030000e+06,2.030000e+06
mean,2.550819e+05,5.501567e+03,4.596870e+01,3.051751e+03,1.723415e+00,...,6.510223e+02,-2.791770e-01,5247.169029,1.498550e+01,4.997059e-01
std,1.414728e+05,5.001288e+03,3.300025e+01,3.694330e+03,1.002725e+00,...,1.142567e+03,4.335100e+00,7963.208181,1.499923e+01,5.000000e-01
min,1.000000e+04,5.000030e+02,-1.000000e+01,-1.342287e+04,1.000000e+00,...,-6.446585e+03,-9.999681e+01,-45940.963963,9.394046e-06,0.000000e+00
25%,1.325128e+05,1.939382e+03,2.000000e+01,7.503747e+02,1.000000e+00,...,9.994857e+01,0.000000e+00,1042.342678,4.313661e+00,0.000000e+00
50%,2.551870e+05,3.968332e+03,4.500000e+01,1.847065e+03,1.000000e+00,...,2.838021e+02,0.000000e+00,2707.467172,1.037510e+01,0.000000e+00
75%,3.775140e+05,7.429375e+03,7.000000e+01,4.096233e+03,2.000000e+00,...,7.410616e+02,0.000000e+00,6409.587903,2.075387e+01,1.000000e+00
max,4.999990e+05,7.548483e+04,1.200000e+02,6.633037e+04,1.100000e+01,...,4.051844e+04,0.000000e+00,225783.759395,2.171939e+02,1.000000e+00

In [25]:
df.describe(include='object')

,transaction_id,product_id,product_category,sub_category,transaction_date,payment_mode,order_status,delivery_date,return_reason,return_date,buyer_state,seller_state,customer_segment,device_type,browser_type,loyalty_member
count,2030000,2030000,2030000,2030000,2030000,1691580,2030000,1624125,304983,304983,2030000,2030000,2030000,2030000,2030000,1351526
unique,2000000,802420,8,38,1096,5,4,1113,6,1123,13,13,3,3,5,2
top,TXN_0000655764,PID_148649,Beauty,Accessories,2022-10-13,COD,Completed,2022-10-26 00:00:00,Better Price Found,2023-06-07 00:00:00,MH,MH,Premium,Mobile,Edge,No
freq,4,13,254260,101674,2010,339161,508301,1605,50944,349,304285,303906,677721,677162,407297,676720

# Missing Values

In [28]:
from enum import unique

nulls = df.isnull().sum()
duplicate = df.duplicated().sum()
dtype = df.dtypes
unique_value = df.nunique()

before_cleaning = pd.DataFrame({
    'Total Null Value' : nulls,
    'Data Value' : dtype,
    'Unique Value' : unique_value
})

before_cleaning

                      Total Null Value Data Value  Unique Value
transaction_id                       0     object       2000000
user_id                              0      int64        481901
product_id                           0     object        802420
product_category                     0     object             8
sub_category                         0     object            38
product_price                        0    float64       2000000
discount_percent                     0      int64            21
final_price                          0    float64       2000000
quantity                             0      int64            11
transaction_date                     0     object          1096
payment_mode                    338420     object             5
order_status                         0     object             4
delivery_date                   405875     object          1113
delivery_days                   405875    float64            13
return_flag                          0      int64             2
return_reason                  1725017     object             6
return_date                    1725017     object          1123
seller_rating                   203413    float64       1635588
customer_rating                 203413    float64       1621415
buyer_state                          0     object            13
seller_state                         0     object            13
customer_segment                     0     object             3
gst_amount                           0    float64       2000000
shipping_cost                    20377    float64         10004
refund_amount                  1725017    float64        300549
device_type                          0     object             3
browser_type                         0     object             5
session_duration_min                 0    float64       2000000
has_reviews                          0      int64             2
loyalty_member                  678474     object             2

In [ ]:
# return_date/return_reason

before = df[['return_date','return_reason']].isnull().sum()
df['return_date'] = df['return_date'].fillna(0)
df['return_reason'] = df['return_reason'].fillna(0)
after = df[['return_date','return_reason']].isnull().sum()

In [32]:
# return_amount

before = df["refund_amount"].isnull().sum()
df["refund_amount"] = df["refund_amount"].fillna(0.0)
after = df["refund_amount"].isnull().sum()
print(f"refund_amount : {before} -> {after} missing")

       refund_amount : 1,725,017 ->       0 missing

In [33]:
# Shipping Cost

before = df["shipping_cost"].isnull().sum()
df["shipping_cost"] = df["shipping_cost"].fillna(0.0)
after  = df["shipping_cost"].isnull().sum()
print(f"       shipping_cost : {before} -> {after} missing")

       shipping_cost : (np.int64(20377),) ->       0 missing

In [34]:
# Loyalty Member

before = df['loyalty_member'].isnull().sum()
df['loyalty_member'] = df['loyalty_member'].fillna('Unknown')
after = df['loyalty_member'].isnull().sum()
print(f'Loyalty Member : {before}   ->   {after} missing')

Loyalty Member : 678474   ->   0 missing

In [35]:
# Delivery Date

before = df['delivery_date'].isnull().sum()
df['delivery_date'] = df['delivery_date'].fillna('Unknown')
after = df['delivery_date'].isnull().sum()
print(f'Delivery Date : {before}   ->   {after} missing')

Delivery Date : 405875   ->   0 missing

In [36]:
# delivery_days

before = df["delivery_days"].isnull().sum()
df["delivery_days"] = df['delivery_days'].fillna(-1)
after  = df["delivery_days"].isnull().sum()
print(f"       shipping_cost : {before} -> {after} missing")

       shipping_cost : 405875 -> 0 missing

In [40]:
# Payment mode

# before = df["shipping_cost"].isnull().sum()
# df["shipping_cost"] = df["shipping_cost"].fillna(0.0)
# after  = df["shipping_cost"].isnull().sum()
# print(f"       shipping_cost : {before} -> {after} missing")

before = df['payment_mode'].isnull().sum()
mode_val = df['payment_mode'].mode()[0]
df['payment_mode'] = df['payment_mode'].fillna(mode_val)
after = df['payment_mode'].isnull().sum()
print(f'Payment Mode : {before}   ->   {after} missing')

Payment Mode : 338420   ->   0 missing

In [41]:
# seller_rating & customer_rating

for col in ["seller_rating", "customer_rating"]:
    before = df[col].isnull().sum()
    overall_median = df[col].median()
    df[col] = df.groupby("product_category")[col].transform(
        lambda x: x.fillna(x.median() if x.notna().any() else overall_median)
    )
    after = df[col].isnull().sum()
    print(f"{col:<20}: {before:>7,}    ->    {after:>7,} missing")

seller_rating       : 203,413    ->          0 missing
customer_rating     : 203,413    ->          0 missing